FROM gazebo-ros:latest

# This image extends from gazebo-ros image to provide support for
# nvidia-docker-plugin

LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
# ENV PATH /usr/lib/nvidia-384/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
#ENV LD_LIBRARY_PATH /usr/lib32/nvidia-384:/usr/lib/nvidia-384:${LD_LIBRARY_PATH}
