FROM gazebo-ros:latest
USER root

ARG ROS_DISTRO_BUILD_TIME

# Bootstrap this repo with the prerelease
RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease bionic main" > /etc/apt/sources.list.d/gazebo-prerelease.list'

# Install the ariac package
RUN apt-get update && apt-get install -y \
        ros-${ROS_DISTRO_BUILD_TIME}-ros-controllers \
        ros-${ROS_DISTRO_BUILD_TIME}-robot-state-publisher \
        ariac3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Needed to use killall
RUN apt-get update && apt-get install -y \
        psmisc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Need to install a specific version of gazebo_ros_pkgs
# 1. Remove official packages
RUN export GZ_VERSION=9 && \
    dpkg -r --force-depends ros-${ROS_DISTRO_BUILD_TIME}-gazebo${GZ_VERSION}-ros-pkgs \
                            ros-${ROS_DISTRO_BUILD_TIME}-gazebo${GZ_VERSION}-ros \
                            ros-${ROS_DISTRO_BUILD_TIME}-gazebo${GZ_VERSION}-plugins \
                            ros-${ROS_DISTRO_BUILD_TIME}-gazebo${GZ_VERSION}-msgs \
                            ros-${ROS_DISTRO_BUILD_TIME}-gazebo${GZ_VERSION}-ros-control

# 2. Build the version from source
RUN mkdir -p /tmp/ros_ws/src
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO_BUILD_TIME}/setup.bash && \
                  cd /tmp/ros_ws/src && \
                  catkin_init_workspace"
RUN git clone \
      https://github.com/osrf/ariac-gazebo_ros_pkgs.git /tmp/ros_ws/src/gazebo_ros_pkgs \
      -b ariac-network-${ROS_DISTRO_BUILD_TIME}
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO_BUILD_TIME}/setup.bash && \
                  cd /tmp/ros_ws/ && \
                  catkin_make -DCMAKE_INSTALL_PREFIX=/opt/ros/${ROS_DISTRO_BUILD_TIME} -j2 install "

# setup entrypoint
COPY ./ariac_entrypoint.sh /
COPY ./run_ariac_task.sh /

USER $USERNAME
ENTRYPOINT ["/ariac_entrypoint.sh"]
