FROM osrf/ros:kinetic-desktop-full

USER root

ARG UBUNTU_DISTRO_TO_BUILD
ARG ROS_DISTRO_BUILD_TIME

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    python-rosdep \
    python-rosinstall \
    python-vcstools \
    wget \
    && rm -rf /var/lib/apt/lists/*
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
RUN echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable ${UBUNTU_DISTRO_TO_BUILD} main" > /etc/apt/sources.list.d/gazebo-stable.list

# Install the ariac package
RUN apt-get update && apt-get install -y \
        ros-${ROS_DISTRO_BUILD_TIME}-ros-core \  
        ros-${ROS_DISTRO_BUILD_TIME}-ros-base \
        ros-${ROS_DISTRO_BUILD_TIME}-catkin \
        ros-${ROS_DISTRO_BUILD_TIME}-ros-controllers \
        ariac \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a new user called ariac-user and give them sudo priviledges.
ENV ROS_DISTRO ${ROS_DISTRO_BUILD_TIME}
ENV USERNAME ariac-user
RUN adduser --gecos "Development User" --disabled-password $USERNAME
RUN adduser $USERNAME sudo
WORKDIR /home/$USERNAME

# setup entrypoint
COPY ./build_team_system.bash /
RUN chmod 755 /build_team_system.bash
COPY ./run_team_system.bash /
RUN chmod 755 /run_team_system.bash

#USER $USERNAME
RUN /build_team_system.bash
ENTRYPOINT ["/run_team_system.bash"]
